export const assessmentClassOptions = ["residential", "condo"];

export const houseStyleOptions = [
  "",
  "2 storey",
  "bungalow",
  "apartment",
  "bilevel",
  "4 level split",
  "other",
  "1 and half storey",
  "3 storey",
  "raised bungalow",
  "2 and half storey",
  "5 level split",
  "3 level split",
];

export const zoningOptions = [
  "RF1",
  "RA7",
  "RSL",
  "RF5",
  "RF4",
  "RF3",
  "RPL",
  "RA8",
  "DC2",
  "DC1",
  "RA9",
  "RF6",
  "RMD",
  "IM",
  "RF2",
  "IB",
  "RMU",
  "RPLt",
  "HVLD",
  "GLG",
  "AG",
  "CB2",
  "UW",
  "DC5",
  "RA8h",
  "TMU",
  "TSLR",
  "CB1",
  "RA7a",
  "HA",
  "CS1",
  "HDR",
  "CO",
  "CS3",
  "RR",
  "GLD",
  "CCLD",
  "RF5g",
  "IH",
  "GHLD",
  "RA9*",
  "CNC",
  "UCRH",
  "AES",
  "EIB",
  "CCA",
  "RF5t",
  "RA7g",
  "RF4t",
  "JAMSC",
  "RMH",
  "CCMD",
  "US",
  "CSC",
  "RF6*",
  "IL",
  "AGU",
  "A",
  "PU",
  "AP",
  "CS4",
  "RA7*",
  "CHY",
  "CMU",
];

export const basementOptions = [
  "",
  "finished",
  "unfinished",
  "partially finished",
  "no basement",
];

export const basementSizeOptions = ["", "Full", "Partial", "Other"];

export const basementStatusOptions = [
  "",
  "Finished",
  "No Basement",
  "Unfinished",
  "Partially Finished",
  "Other",
];

export const basement2StatusOptions = [
  "",
  "Fully Finished",
  "Partly Finished",
  "Unfinished",
  "No Basement",
];

export const garageOptions = [
  { label: "No", value: "0" },
  { label: "Yes", value: "1" },
];

export const exteriorOptions = [
  "Wood",
  "Brick",
  "Vinyl",
  "Stone",
  "Other",
  "Metal",
  "Stucco",
  "Concrete",
];

export const floorOptions = [
  "Ceramic Tile",
  "Laminate Flooring",
  "Linoleum",
  "Hardwood",
  "Carpet",
];

export const neighbourhoodOptions = [
  "Oliver",
  "Summerside",
  "Chappelle Area",
  "The Hamptons",
  "Queen Mary Park",
  "Windermere",
  "Walker",
  "Downtown",
  "Rutherford",
  "Mc Conachie Area",
  "South Terwillegar",
  "Laurel",
  "Alberta Avenue",
  "Ottewell",
  "Parkdale",
  "Boyle Street",
  "Strathcona",
  "Silver Berry",
  "Ambleside",
  "Klarvatten",
  "Inglewood",
  "Glastonbury",
  "Eastwood",
  "Ormsby Place",
  "Westmount",
  "Bonnie Doon",
  "Daly Grove",
  "Wild Rose",
  "Kiniski Gardens",
  "Cromdale",
  "Charlesworth",
  "Baturyn",
  "Dunluce",
  "Allard",
  "Jasper Park",
  "Secord",
  "Belvedere",
  "Britannia Youngstown",
  "Casselman",
  "Balwin",
  "Strathearn",
  "Lymburn",
  "Caernarvon",
  "Fraser",
  "Glenwood",
  "Central Mc Dougall",
  "Canora",
  "The Orchards At Ellerslie",
  "Cumberland",
  "Macewan",
  "Belmont",
  "Edgemont",
  "Ellerslie",
  "Rosenthal",
  "Glenora",
  "Calder",
  "Carlton",
  "Tipaskan",
  "Queen Alexandra",
  "Twin Brooks",
  "La Perle",
  "Royal Gardens",
  "Pollard Meadows",
  "Haddow",
  "Griesbach",
  "King Edward Park",
  "Kirkness",
  "Tamarack",
  "Maple",
  "Forest Heights",
  "Evansdale",
  "Ritchie",
  "Brintnell",
  "Clareview Town Centre",
  "Kensington",
  "Garneau",
  "Terwillegar Towne",
  "Bisset",
  "York",
  "Hollick Kenyon",
  "Beacon Heights",
  "Keheewin",
  "Jackson Heights",
  "Oxford",
  "Larkspur",
  "Glenridding Heights",
  "West Meadowlark Park",
  "Glengarry",
  "Schonsee",
  "Matt Berry",
  "Wellington",
  "Killarney",
  "Montrose",
  "Allendale",
  "Kildare",
  "Beaumaris",
  "Mayfield",
  "Pleasantview",
  "Mc Cauley",
  "Kilkenny",
  "Homesteader",
  "Duggan",
  "Magrath Heights",
  "Sakaw",
  "Athlone",
  "Weinlos",
  "Lago Lindo",
  "Crawford Plains",
  "Jamieson Place",
  "Spruce Avenue",
  "Northmount",
  "Meadowlark Park",
  "Sweet Grass",
  "Rosslyn",
  "Bulyea Heights",
  "Belmead",
  "Miller",
  "Laurier Heights",
  "Kernohan",
  "Rapperswill",
  "Grovenor",
  "Aldergrove",
  "Eaux Claires",
  "Terra Losa",
  "Satoo",
  "Parkview",
  "Meyonohk",
  "Hillview",
  "Granville",
  "Elmwood Park",
  "Brander Gardens",
  "Beverly Heights",
  "Michaels Park",
  "Greenfield",
  "Newton",
  "Trumpeter Area",
  "Capilano",
  "Mc Kernan",
  "Delwood",
  "Belle Rive",
  "Holyrood",
  "Elsinore",
  "Canossa",
  "Tawa",
  "Prince Charles",
  "Fulton Place",
  "Carlisle",
  "Kenilworth",
  "Callingwood South",
  "Paisley",
  "Lauderdale",
  "Parkallen",
  "Greenview",
  "Mactaggart",
  "Blue Quill",
  "Canon Ridge",
  "Hazeldean",
  "Callaghan",
  "Ermineskin",
  "West Jasper Place",
  "Highlands",
];

export const foundationOptions = ["Concrete Perimeter", "Other"];

export const heatOptions = ["Forced Air", "Other", "Natural Gas"];

export const roofOptions = ["Asphalt Shingles", "Other"];

export const extraOptions = [
  "Garage Control",
  "Other",
  "Air Conditioning-Central",
  "Dishwasher-Built-In",
  "Microwave Hood Fan",
  "Stove-Electric",
  "Garage Opener",
  "Refrigerator",
  "Window Coverings",
  "Hood Fan",
  "Washer",
  "Dryer",
];
